### ISSUE TITLE
Delete project error sometimes

### ISSUE THREAD

**Issue by whysqwhw** [angelozerr/tern.java#401] opened 2016-02-05 03:26 UTC
Delete project in eclipse, sometimes  appear an error popup window, prompt  '.tern-project' file is still being used, may be cased by FileReader  in TernProject.doLoad() is not closed.

**Comment by lmoretto** [comment] 2016-02-16 17:23
I have the same issue. Every time i try to delete an eclipse project with Tern nature, I get an error saying that the '.tern-project' file could not be deleted because it is still being used.

As @whysqwhw says, this seems to be caused by the FileReader in TernProject.doLoad() not being properly closed. I tried to change that piece of code with a finally block where the reader is closed and the problem has disappeared.

@angelozerr if required, I can provide a pull reqeust with a simple patch for this problem. However, do you think it would be possible to release a new version (e.g. 1.1.1) just with this patch?

**Comment by angelozerr** [comment] 2016-02-16 23:40
> I can provide a pull reqeust

yes please.

> release a new version (e.g. 1.1.1) just with this patch

No sorry. I would like to release 1.2.0, but I must finish some work on AngularJS Eclipse before.

**Comment by lmoretto** [comment] 2016-02-17 08:35
Ok, I will provide the pull request today.

I was asking to release a new version this because this issue also affects current 1.1.0 release.

**Comment by angelozerr** [comment] 2016-03-11 08:11
@lmoretto can I close this issue?

**Comment by lmoretto** [comment] 2016-03-11 08:14
@angelozerr  Yes, I think that your commit d694c3e properly solved this issue.

**Comment by angelozerr** [comment] 2016-03-11 08:18
Ok, thanks for your answer. I close this issue. Reopen it if you have problem again by adding more info to reproduce the problem.

**Closed by angelozerr** 2016-03-11 08:18 UTC
