### ISSUE TITLE
Tern ESLint Arrow Function Issues (from 2.3.0 eslint)

### ISSUE THREAD

**Issue by Knight-Yoshi** [angelozerr/tern.java#409] opened 2016-03-05 09:29 UTC
So with ESLint (in Tern) I'm getting errors about arrow functions and classes, I do not get the error notices when using ESLint from the command line.
eslint.json
```
{
	"extends": "eslint:recommended",
	"root": true,
	"parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
			"blockBindings": true,
			"forOf": true,
			"jsx": true
		}
    },
	"rules": {
		"arrow-parens": [2, "always"],
		"arrow-spacing": [1, { "before": true, "after": true }],
		"comma-dangle": [1, "always-multiline"],
		"eqeqeq": [2, "allow-null"],
		"quotes": [2, "single"],
		"no-console": 0,
		"no-duplicate-case": 2,
		"no-empty-character-class": 2,
		"no-extra-parens": 1,
		"no-extra-semi": 1,
		"no-invalid-regexp": 2,
		"no-irregular-whitespace": 2,
		"no-mixed-spaces-and-tabs": [1, "smart-tabs"],
		"no-negated-in-lhs": 2,
		"no-redeclare": 2,
		"no-sparse-arrays": 2,
		"no-this-before-super": 2,
		"no-unused-vars": 1,
		"semi": [2, "always"],
		"use-isnan": 2
	},
	"ecmaFeatures": {
		"regexYFlag": true,
		"regexUFlag": true
	},
	"env": {
		"es6": true,
		"browser": true,
		"jquery": true
	},
	"globals": {
		"jQuery": false,
		"chrome": false,
		"Foundation": false,
	}
}
```

test.js
```
var promise = new Promise ((resolve, reject) => {
	resolve();
});

promise.then((res) => {
	// do stuff
}).catch((rej) => {
	
});

class hello {
	constructor () {
		this.world();
	}
	
	world () {
		console.log('Hello World');
	}
}
```

Tern
```
- Syntax error on token ">", invalid FunctionExpressionHeader (creating the promise)
- Syntax error on token ">", delete this token (.then( (res) => ...)
- Syntax error on token ">", delete this token (.catch( (rej) => ...)
- Syntax error on token "catch", Identifier expected
- Syntax error on token "hello", ; expected
```

What I get in the command line
```
  1:38  warning  'reject' is defined but never used  no-unused-vars
  5:15  warning  'res' is defined but never used     no-unused-vars
  9:7   warning  'hello' is defined but never used   no-unused-vars
```

**Comment by angelozerr** [comment] 2016-03-05 11:14
Do you use the same version of ESLint with command line than tern-eslint https://github.com/angelozerr/tern-eslint/blob/master/package.json#L18

**Comment by Knight-Yoshi** [comment] 2016-03-05 15:00
I have v2.3.0 (updated just yesterday, March 4th) for command line ESLint.

**Comment by angelozerr** [comment] 2016-03-05 15:11
Try to remove at hand eslint of tern-eslint with your version. You can find tern-eslint in your ECLIPSE_HOME/plugins/ternjs***/node_modules

**Comment by Knight-Yoshi** [comment] 2016-03-06 16:05
I'm attempting to, but of course it wouldn't be as simple as replacing the tern-eslint/node_modules/eslint directory with the latest one.

**Comment by angelozerr** [comment] 2016-03-06 17:19
@Knight-Yoshi I have started to use 2.3.0 eslint inside tern-eslint, but "fix" doesn't work? See https://travis-ci.org/angelozerr/tern-eslint#L261

I have no time to study the problem. It should be cool if you could help me to fix the problem. The test which causes the problem is https://github.com/angelozerr/tern-eslint/blob/master/test/issues.js#L22

**Comment by angelozerr** [comment] 2016-03-06 18:40
@Knight-Yoshi forget my last comment. Once job https://opensagres.ci.cloudbees.com/job/tern.java/872/ will be finished, please reinstall tern.java and tell me if it works for you. Thanks.

**Comment by Knight-Yoshi** [comment] 2016-03-07 01:41
After uninstalling and reinstalling Tern this is the error I get

```
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
            ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at new Config (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern-eslint/node_modules/eslint/lib/config.js:194:54)
    at ESLintConfig.update (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern-eslint/eslint.js:255:23)
    at new ESLintConfig (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern-eslint/eslint.js:242:12)
    at null.eslint (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern-eslint/eslint.js:263:15)
    at Object.signal.mixin.loadPlugin (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern/lib/tern.js:209:31)
    at Object.exports.Server (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern/lib/tern.js:124:12)
    at startServer (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern/bin/tern:171:16)
    at Object.<anonymous> (/Applications/Eclipse.app/Contents/Eclipse/plugins/ternjs_1.2.0.201603061847/node_modules/tern/bin/tern:166:14)
    at Module._compile (module.js:460:26)
```

**Comment by angelozerr** [comment] 2016-03-07 06:34
That's stange it works for me and I have no done some midificatiob about the load of eslint.json? Could you share your project please?

**Comment by angelozerr** [comment] 2016-03-07 11:14
Ok forget my last comment. Please reinstall tern.java once https://opensagres.ci.cloudbees.com/job/tern.java/875/ will be finished.

**Comment by Knight-Yoshi** [comment] 2016-03-07 14:27
Sorry for the late replies, it's working now. Good job at getting ESLint fixed so quickly though! 

Off-topic question. Is highlight suppose to highlight every instance of a function/variable or syntax highlighting? There's no description or anything and as far as I can tell it doesn't do anything so I was just curious.

**Comment by angelozerr** [comment] 2016-03-11 08:10
@Knight-Yoshi please create an other issue with your question with more detail. Thanks.

I close this issue.

**Closed by angelozerr** 2016-03-11 08:10 UTC
